### PR TITLE
spacy-annotator v2?

### PR DESCRIPTION
**Pull request by dayalstrub-cma**
This is a rewrite of spacy-annotator to use spacy functionality more fully (pre-populating of annotations and displacy). It also does some spring cleaning and unfortunately in so doing it's lost it's list_annotator functionality, but I think it works quite well. let me know what you think.

fixes

* missing pandas requirement
* overwriting of annotation column in dataframe if already present
* always shuffled
* un-pins SpaCy, so can have 3.0

adds

* models passed rather than model name as string, so allows to pass custom models/NER, eg with EntityRuler
* pre-populating of entities using spacy model supplied
* text visualised using spacy.displacy to view current entities
* label input changed from TextArea to Text as simpler and avoids user mistakes
* uses spacy for add_annotation, which feels more aligned with the rest now and more extensible in future, also avoids copying filter_spans code

TODO

- [ ] ~reinstate list annotate~
- [ ] ~test~
- [ ] update demo gif

### CODE REVIEW

**Comment by ieriii** [comment]
Thank you, Dayal :-)
I'll review the PR soon.

**Comment by ieriii** [comment]
Nice pull request! Thank you for taking the time!

I have a couple of comments:
1. Displacy has a very nice UI (i.e. the colours are sleek!). However, I noted the user cannot copy the values and paste them into the form. Is it just me/my laptop/ my IDE? 

I think ability to copy and paste can be quite important for text containing a large amount of misspelled words/entities. It can be bit unnatural/prone to error having to write misspelled entities in the annotator yourself. Happy to be convinced otherwise.

2. can we remove the null? I can have a go if you do not have time. This is a picky comment, I know :)
spacy-annotator_null

**Comment by dayalstrub-cma** [comment]
Thanks for the review.

Re. your points

1. I don't have issues copying either the highlighted text (which however is also pre-populated in annotations, so you would not need to copy) or the text that is not highlighted in JupyterLab 3.X. And I think it has also been used in some Jupyter notebooks, but don't know the version. What IDE are you using?
2. I have figured out the `null`. It was really annoying me too!

I have also 

i. found some sneaky prints in `__add_annotation` that i forgot to remove 😅 
ii. been thinking about an even bigger refactor to deal with some issues, e.g. default `English` model is not as "neutral" as I had hoped and it's tokenizer might not work for some languages so maybe best always ask for a model, etc. BUT I think we can fix these issues in future, smaller PRs.

**Comment by ieriii** [comment]
Thanks Dayal.
Nice! I agree with your points.

I'm using VSCode as my IDE. I'll double check whether I can do something about it.
I'll review and the merge.

🚀

**Comment by dayalstrub-cma** [comment]
@ieriii sorry. completely forgot I needed to make fixes. got notified yesterday that you cleaned everything up and sorted it out. looks good! thanks

**Comment by ieriii** [comment]
Thank you, great PR 🚀  
Happy to collaborate more on this or other projects.

**Pull request merged**
